import React, { useState } from "react";
import TableSelectSeat from "./TableSelectSeat";
import TypeSeat from "./TypeSeat";
import DisplayTable from "./DisplayTable";

const Home = () => {
  let [formData, setFormData] = useState({
    name: "",
    numberSeat: "",
  });
  let [selecting, setSelecting] = useState(false);
  let [selectedSeats, setSelectedSeats] = useState([]);
  let [showSeats, setShowSeat] = useState(false);

  let handleInput = (e) => {
    let { value, name } = e.target;
    setFormData((prevData) => ({
      ...prevData,
      [name]: value,
    }));
  };
  let handleSubmit = (e) => {
    e.preventDefault();

    if (!formData.name || !formData.numberSeat) {
      alert("Please Enter your Name and Number of Seats");
    }
    setSelecting(true);
    setShowSeat(true);

    setSelectedSeats((prevSeats) => {
      if (prevSeats.includes(e)) {
        return prevSeats.filter((s) => s !== e); // Bỏ chọn nếu ghế đã được chọn
      } else {
        // Kiểm tra nếu số lượng ghế đã đạt giới hạn
        if (prevSeats.length < parseInt(formData.numberSeat)) {
          return [...prevSeats, e];
        }
        alert("Số lượng ghế đã đạt tối đa");
        return prevSeats;
      }
    });
  };
  const handleConfirmSelection = () => {
    setShowMessage(false);
    setSelecting(false);
    alert(
      `Tên: ${formData.name}, Số ghế: ${selectedSeats.join(", ")}, Giá: ${
        selectedSeats.length * seatPrice
      } VND`
    );
  };

  return (
    <>
      <div className="home_heading fw-bold text-center">
        <h1 className="text-uppercase text-warning">
          Đặt vé xem Phim CyberLearn.vn
        </h1>
        <p className="home_heading-screen text-light fs-3">Màng Hình</p>
      </div>
      <div className="home mx-auto">
        <form className="input-form" onSubmit={handleSubmit}>
          <div className="home-input d-flex justify-content-center">
            <div className="home_left ">
              <label htmlFor="name" className=" fs-5  fw-semibold">
                Name
                <span className="bg-red-500 px-1">*</span>
              </label>
              <input
                onChange={handleInput}
                data-type="name"
                id="name"
                name="name"
                type="text"
                className="home-input_name"
              />
            </div>
            <div className="home_right ">
              <label htmlFor="numberSeat" className="  ms-3 fs-5  fw-semibold ">
                Number of seat
                <span className="bg-red-500 px-1">*</span>
              </label>
              <input
                onChange={handleInput}
                data-type="numberSeat"
                id="numberSeat"
                name="numberSeat"
                type="number"
                className="home-input_seat"
              />
            </div>
          </div>
          <button className="home_button">Start selecting</button>
        </form>
        {/* <TypeSeat /> */}
        <ul className="mt-3">
          <li className="seat_status seat_status-green">Selected Seat</li>
          <li className="seat_status seat_status-red">Reserved Seat</li>
          <li className="seat_status seat_status-white">Empty Seat</li>
        </ul>
        <div className="home_body text-center mx-auto">
          <p id="notification"></p>
          {/* <TableSelectSeat /> */}
          <table className="table_seat text-center">
            <tbody>
              <tr>
                <td></td>
                <td>1</td>
                <td>2</td>
                <td>3</td>
                <td>4</td>
                <td>5</td>
                <td>6</td>
                <td>7</td>
                <td>8</td>
                <td>9</td>
                <td>10</td>
                <td>11</td>
                <td>12</td>
              </tr>
              <tr>
                <td>A</td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"A1"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"A2"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"A3"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"A4"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"A5"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"A6"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"A7"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"A8"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"A9"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"A10"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"A11"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"A12"}
                    disabled
                  />
                </td>
              </tr>
              <tr>
                <td>B</td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"B1"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"B2"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"B3"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"B4"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"B5"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"B6"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"B7"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"B8"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"B9"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"B10"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"B11"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"B12"}
                    disabled
                  />
                </td>
              </tr>
              <tr>
                <td>C</td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"C1"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"C2"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"C3"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"C4"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"C5"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"C6"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"C7"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"C8"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"C9"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"C10"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"C11"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"C12"}
                    disabled
                  />
                </td>
              </tr>
              <tr>
                <td>D</td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"B1"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"B2"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"B3"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"B4"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"B5"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"B6"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"B7"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"B8"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"B9"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"B10"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"B11"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"B12"}
                    disabled
                  />
                </td>
              </tr>
              <tr>
                <td>E</td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"E1"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"E2"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"E3"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"E4"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"E5"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"E6"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"E7"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"E8"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"E9"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"E10"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"E11"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"E12"}
                    disabled
                  />
                </td>
              </tr>
              <tr>
                <td>F</td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"F1"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"F2"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"F3"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"F4"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"F5"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"F6"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"F7"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"F8"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"F9"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"F10"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"F11"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"F12"}
                    disabled
                  />
                </td>
              </tr>
              <tr>
                <td>G</td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"G1"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"G2"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"G3"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"G4"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"G5"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"G6"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"G7"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"G8"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"G9"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"G10"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"G11"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"G12"}
                    disabled
                  />
                </td>
              </tr>
              <tr>
                <td>H</td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"H1"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"H2"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"H3"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"H4"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"H5"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"H6"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"H7"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"H8"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"H9"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"H10"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"H11"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"H12"}
                    disabled
                  />
                </td>
              </tr>
              <tr>
                <td>I</td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"I1"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"I2"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"I3"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"I4"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"I5"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"I6"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"I7"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"I8"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"I9"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"I10"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"I11"}
                    disabled
                  />
                </td>
                <td>
                  <input
                    type="checkbox"
                    name=""
                    className="seats"
                    value={"I12"}
                    disabled
                  />
                </td>
              </tr>
            </tbody>
          </table>
          <div
            className="screen w-full my-5"
            style={{ backgroundColor: "#ff9800" }}
          >
            <h2 className="screen_title">Screen this way</h2>
          </div>
          <button onChange={handleStartSelecting} className="home_button">
            Confirm Selection
          </button>
        </div>
        {/* <DisplayTable /> */}
        <div className="displayBox text-center mx-auto mt-3">
          <table className="displayTable ">
            <tbody>
              <tr>
                <th>Name</th>
                <th>Number of Seats</th>
                <th>Seats</th>
                <th>Price</th>
              </tr>
              <tr>
                <td>
                  <textarea name="" id="nameDisplay" disabled></textarea>
                </td>
                <td>
                  <textarea name="" id="numberDisplay" disabled></textarea>
                </td>
                <td>
                  <textarea name="" id="seatsDisplay" disabled></textarea>
                </td>
                <td>
                  <textarea name="" id="seatsPrice" disabled></textarea>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </>
  );
};

export default Home;
