import React from "react";

const TableSelectSeat = () => {
  return (
    <table className="table_seat text-center">
      <tbody>
        <tr>
          <td></td>
          <td>1</td>
          <td>2</td>
          <td>3</td>
          <td>4</td>
          <td>5</td>
          <td>6</td>
          <td>7</td>
          <td>8</td>
          <td>9</td>
          <td>10</td>
          <td>11</td>
          <td>12</td>
        </tr>
        <tr>
          <td>A</td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"A1"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"A2"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"A3"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"A4"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"A5"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"A6"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"A7"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"A8"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"A9"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"A10"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"A11"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"A12"}
              disabled
            />
          </td>
        </tr>
        <tr>
          <td>B</td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"B1"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"B2"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"B3"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"B4"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"B5"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"B6"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"B7"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"B8"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"B9"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"B10"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"B11"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"B12"}
              disabled
            />
          </td>
        </tr>
        <tr>
          <td>C</td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"C1"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"C2"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"C3"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"C4"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"C5"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"C6"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"C7"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"C8"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"C9"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"C10"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"C11"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"C12"}
              disabled
            />
          </td>
        </tr>
        <tr>
          <td>D</td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"B1"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"B2"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"B3"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"B4"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"B5"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"B6"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"B7"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"B8"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"B9"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"B10"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"B11"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"B12"}
              disabled
            />
          </td>
        </tr>
        <tr>
          <td>E</td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"E1"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"E2"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"E3"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"E4"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"E5"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"E6"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"E7"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"E8"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"E9"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"E10"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"E11"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"E12"}
              disabled
            />
          </td>
        </tr>
        <tr>
          <td>F</td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"F1"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"F2"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"F3"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"F4"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"F5"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"F6"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"F7"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"F8"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"F9"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"F10"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"F11"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"F12"}
              disabled
            />
          </td>
        </tr>
        <tr>
          <td>G</td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"G1"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"G2"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"G3"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"G4"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"G5"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"G6"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"G7"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"G8"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"G9"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"G10"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"G11"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"G12"}
              disabled
            />
          </td>
        </tr>
        <tr>
          <td>H</td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"H1"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"H2"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"H3"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"H4"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"H5"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"H6"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"H7"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"H8"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"H9"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"H10"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"H11"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"H12"}
              disabled
            />
          </td>
        </tr>
        <tr>
          <td>I</td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"I1"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"I2"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"I3"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"I4"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"I5"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"I6"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"I7"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"I8"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"I9"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"I10"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"I11"}
              disabled
            />
          </td>
          <td>
            <input
              type="checkbox"
              name=""
              className="seats"
              value={"I12"}
              disabled
            />
          </td>
        </tr>
      </tbody>
    </table>
  );
};

export default TableSelectSeat;
